package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name="Catalog")
public class Catalog  implements java.io.Serializable {

	@Id
	@Column( name = "Catalog_ID" )
     private String catalogId;
	
	@Column(name = "name", nullable = false)
     private String name;
     
	@Column( name = "description" )
	@Lob
     private byte[] description;

    public Catalog() {
    }

	
    public Catalog(String catalogId, String name) {
        this.catalogId = catalogId;
        this.name = name;
    }
    public Catalog(String catalogId, String name, byte[] description) {
       this.catalogId = catalogId;
       this.name = name;
       this.description = description;
    }
   
    public String getCatalogId() {
        return this.catalogId;
    }
    
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getDescription() {
        return this.description;
    }
    
    public void setDescription(byte[] description) {
        this.description = description;
    }
    
    public String toString(){
    	
    	StringBuffer sb= new StringBuffer();
    	
    	sb.append("catalogId: ");
    	sb.append(catalogId);
    	sb.append("\n");
    	sb.append("name: ");
    	sb.append(name);
    	sb.append("\n");
    	
    	if(description != null){
    		sb.append("description: ");
        	sb.append(description.toString());
    	}
    	
    	return sb.toString();
    }
    
}


