package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * CategoryMasterProductId generated by hbm2java
 */
public class CategoryMasterProductId  implements java.io.Serializable {


     private String categoryId;
     private String masterProductId;

    public CategoryMasterProductId() {
    }

    public CategoryMasterProductId(String categoryId, String masterProductId) {
       this.categoryId = categoryId;
       this.masterProductId = masterProductId;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getMasterProductId() {
        return this.masterProductId;
    }
    
    public void setMasterProductId(String masterProductId) {
        this.masterProductId = masterProductId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryMasterProductId) ) return false;
		 CategoryMasterProductId castOther = ( CategoryMasterProductId ) other; 
         
		 return ( (this.getCategoryId()==castOther.getCategoryId()) || ( this.getCategoryId()!=null && castOther.getCategoryId()!=null && this.getCategoryId().equals(castOther.getCategoryId()) ) )
 && ( (this.getMasterProductId()==castOther.getMasterProductId()) || ( this.getMasterProductId()!=null && castOther.getMasterProductId()!=null && this.getMasterProductId().equals(castOther.getMasterProductId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoryId() == null ? 0 : this.getCategoryId().hashCode() );
         result = 37 * result + ( getMasterProductId() == null ? 0 : this.getMasterProductId().hashCode() );
         return result;
   }   


}


