package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="Category")
public class Category  implements java.io.Serializable {

	@Id
	@Column(name = "Category_ID", nullable = false)
     private String categoryId;
	
	@Column(name = "name", nullable = false)
     private String name;
	
	@Column(name = "description")
     private byte[] description;
	
	@Column(name = "Catalog_ID", nullable = false)
     private String catalogId;
     
	@Column(name = "Parent_Category_ID")
     private String parentCategoryId;

    public Category() {
    }

	
    public Category(String categoryId, String name, String catalogId) {
        this.categoryId = categoryId;
        this.name = name;
        this.catalogId = catalogId;
    }
    public Category(String categoryId, String name, byte[] description, String catalogId, String parentCategoryId) {
       this.categoryId = categoryId;
       this.name = name;
       this.description = description;
       this.catalogId = catalogId;
       this.parentCategoryId = parentCategoryId;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getDescription() {
        return this.description;
    }
    
    public void setDescription(byte[] description) {
        this.description = description;
    }
    public String getCatalogId() {
        return this.catalogId;
    }
    
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }
    public String getParentCategoryId() {
        return this.parentCategoryId;
    }
    
    public void setParentCategoryId(String parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }




}


