package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * CategoryMasterProduct generated by hbm2java
 */
public class CategoryMasterProduct  implements java.io.Serializable {


     private CategoryMasterProductId id;

    public CategoryMasterProduct() {
    }

    public CategoryMasterProduct(CategoryMasterProductId id) {
       this.id = id;
    }
   
    public CategoryMasterProductId getId() {
        return this.id;
    }
    
    public void setId(CategoryMasterProductId id) {
        this.id = id;
    }




}


