package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * CategoryProduct generated by hbm2java
 */
public class CategoryProduct  implements java.io.Serializable {


     private CategoryProductId id;

    public CategoryProduct() {
    }

    public CategoryProduct(CategoryProductId id) {
       this.id = id;
    }
   
    public CategoryProductId getId() {
        return this.id;
    }
    
    public void setId(CategoryProductId id) {
        this.id = id;
    }




}


