package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * CategoryProductId generated by hbm2java
 */
public class CategoryProductId  implements java.io.Serializable {


     private String categoryId;
     private String productId;

    public CategoryProductId() {
    }

    public CategoryProductId(String categoryId, String productId) {
       this.categoryId = categoryId;
       this.productId = productId;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryProductId) ) return false;
		 CategoryProductId castOther = ( CategoryProductId ) other; 
         
		 return ( (this.getCategoryId()==castOther.getCategoryId()) || ( this.getCategoryId()!=null && castOther.getCategoryId()!=null && this.getCategoryId().equals(castOther.getCategoryId()) ) )
 && ( (this.getProductId()==castOther.getProductId()) || ( this.getProductId()!=null && castOther.getProductId()!=null && this.getProductId().equals(castOther.getProductId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoryId() == null ? 0 : this.getCategoryId().hashCode() );
         result = 37 * result + ( getProductId() == null ? 0 : this.getProductId().hashCode() );
         return result;
   }   


}


