package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * LovPropertyVarchar256 generated by hbm2java
 */
public class LovPropertyVarchar256  implements java.io.Serializable {


     private Integer id;
     private String value;
     private int propertyId;

    public LovPropertyVarchar256() {
    }

    public LovPropertyVarchar256(String value, int propertyId) {
       this.value = value;
       this.propertyId = propertyId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }




}


