package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * MasterProduct generated by hbm2java
 */
public class MasterProduct  implements java.io.Serializable {


     private String masterProductId;
     private String name;
     private byte[] description;

    public MasterProduct() {
    }

	
    public MasterProduct(String masterProductId, String name) {
        this.masterProductId = masterProductId;
        this.name = name;
    }
    public MasterProduct(String masterProductId, String name, byte[] description) {
       this.masterProductId = masterProductId;
       this.name = name;
       this.description = description;
    }
   
    public String getMasterProductId() {
        return this.masterProductId;
    }
    
    public void setMasterProductId(String masterProductId) {
        this.masterProductId = masterProductId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getDescription() {
        return this.description;
    }
    
    public void setDescription(byte[] description) {
        this.description = description;
    }




}


