package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * ProductPropertyVarchar256Value generated by hbm2java
 */
public class ProductPropertyVarchar256Value  implements java.io.Serializable {


     private Integer id;
     private int propertyId;
     private String productId;
     private String value;

    public ProductPropertyVarchar256Value() {
    }

	
    public ProductPropertyVarchar256Value(int propertyId, String productId) {
        this.propertyId = propertyId;
        this.productId = productId;
    }
    public ProductPropertyVarchar256Value(int propertyId, String productId, String value) {
       this.propertyId = propertyId;
       this.productId = productId;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


