package com.app.hibernate.srcs;
// Generated Oct 6, 2017 3:23:39 PM by Hibernate Tools 4.3.1.Final



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String productId;
     private String name;
     private String masterProductId;
     private byte[] description;

    public Product() {
    }

	
    public Product(String productId, String name) {
        this.productId = productId;
        this.name = name;
    }
    public Product(String productId, String name, String masterProductId, byte[] description) {
       this.productId = productId;
       this.name = name;
       this.masterProductId = masterProductId;
       this.description = description;
    }
   
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMasterProductId() {
        return this.masterProductId;
    }
    
    public void setMasterProductId(String masterProductId) {
        this.masterProductId = masterProductId;
    }
    public byte[] getDescription() {
        return this.description;
    }
    
    public void setDescription(byte[] description) {
        this.description = description;
    }




}


