SITE_NAME = "converse"
CONFOO_DIR = File.dirname(__FILE__) + "/"
SITE_TEMPLATE = CONFOO_DIR + "site_template/"
CARTRIDGE_DIR = CONFOO_DIR + "cartridges/"
CORE_CARTRIDGE_DIR = CARTRIDGE_DIR + "converse_core/cartridge/"
EMEA_CARTRIDGE_DIR = CARTRIDGE_DIR + "converse_emea/cartridge/"

US_SITE_ID = 'converse'
DE_SITE_ID = 'converse-de'
GB_SITE_ID = 'converse-gb'
FR_SITE_ID = 'converse-fr'
BE_SITE_ID = 'converse-be'
ES_SITE_ID = 'converse-es'
NL_SITE_ID = 'converse-nl'
IT_SITE_ID = 'converse-it'

import 'tools/build_util.rb'

import 'tools/dev.rake'
import 'tools/frontend.rake'

task :default                           => "frontend:developer_build"
# below tasks are kept for back compatibility
task :prepush_test                      => "frontend:developer_build_minimal"
task :frontend_developer_build, [:host] => "frontend:developer_build"
task :frontend_master_build,    [:host] => "frontend:production_build"
