source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'pg', '0.15.1'
gem 'nokogiri'
gem 'unicorn'
gem 'curb'
gem 'devise'
gem 'test-unit'

group :assets do
	gem 'sass-rails', '~> 3.2.3'
end

group :test do
    gem 'simplecov'
end
