#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'rubygems'
require File.expand_path('../config/application', __FILE__)

NikeomsParser::Application.load_tasks

# DISABLE DB Rake Tasks - BEGIN
# Do not mess with DB. DataHub is in charge of DB.
#
Rake::TaskManager.class_eval do
  def delete_task(task_name)
    @tasks.delete(task_name.to_s)
  end
  
  Rake.application.delete_task("db:test:purge")
  Rake.application.delete_task("db:schema:load")
  
end

namespace :db do
    namespace :test do
        task :purge do 
        end
    end
    
    namespace :schema do
        task :load do 
        end
    end
    
end
# DISABLE DB Rake Tasks - END